### ISSUE TITLE
F# logo use

### ISSUE THREAD

**Issue by cmeeren** [cmeeren/Facil#1]
@reedcopsey This is a project for strongly typed access to SQL server. I am considering a logo like the below (not necessarily final colors/proportions). Is that an acceptable use of the F# logo elements? (Related: https://github.com/cmeeren/Felicity/issues/1)

![Logo](https://user-images.githubusercontent.com/7766733/102489752-33870900-406e-11eb-9f51-8fac8b2c8355.png)

**Comment by ReedCopsey** [comment]
@cmeeren I think this is fine. Thank you for checking.

**Comment by cmeeren** [comment]
Thanks a lot!
