### ISSUE TITLE
Invalid path breaks Linux build when adding Facil package

### ISSUE THREAD

**Issue by schauerte** [cmeeren/Facil#12]
After adding Facil to a new net5.0 console application on Linux, `dotnet build` fails, because the Facil.Generator.dll can not be found.

After manual checking I can confirm, that the search path seems correct, but the FacilGenerate.targets file contains an invalid path separator. Changing the file manually allows the build to succeed.

I've not tested on Windows, but I assume, using a slash "/" instead of backslash "\\" will work there too. So I suggest replacing  the backslash in [Facil.Package/FacilGenerate.targets](https://github.com/cmeeren/Facil/blob/84594933c124fda9561488e319f8c289f0ce716a/src/Facil.Generator/FacilGenerate.targets) with a slash (like already used in  [Facil.Generator/FacilGenerate.targets](https://github.com/cmeeren/Facil/blob/84594933c124fda9561488e319f8c289f0ce716a/src/Facil.Generator/FacilGenerate.targets)).

Thank you very much.

**Comment by cmeeren** [comment]
Thanks. I'll see if that works on Windows.

**Comment by cmeeren** [comment]
Seems it works fine on Windows. I have pushed the fix to `master`. Are you able to try it out before I publish it? Just build and pack the Facil.Package project, and you'll get a nuget in the nupkg folder in the repo root. You can consume that in a project using a local package source [as shown here](https://github.com/cmeeren/Facil/blob/master/nuget.config). Note that you have to delete the cached "unpacked" Facil version you likely have in your local NuGet cache (`~/.nuget` I suppose).

The target files in Facil.Package were old and unused; I didn't know they were still around. I have deleted them now.

**Comment by schauerte** [comment]
This is strange:
* I was able to build and pack after replacing some more backslashes in Facil.package.fsproj
* I've configured the nuget source and deleted the cached version from `~/.nuget`
* `dotnet restore` succeeded and the `1.3.0` folder reappeared (below `~/.nuget`)
* The FacilGenerate.targets file looks correct but 
* `dotnet build` fails, because the tools folder does not contain any subfolders (only the FacilGenerate.targets files) - so .nuget/packages/facil/1.3.0/tools/netcoreapp3.1/Facil.Generator.dll is missing

Maybe this is some other path issue but I'm not sure where to look.

**Comment by cmeeren** [comment]
Can you try with this nupkg from the CI build? https://ci.appveyor.com/project/cmeeren/facil/builds/38305842/artifacts

(Remember to again delete the cached one in `~/.nuget`.)

If you succeed with that, I am comfortable releasing this and chalking your new problems up to local build/env stuff.

**Comment by schauerte** [comment]
Yes! This nupkg works perferctly fine.

I also agree that local build/env stuff prevents me from building/packing Facil properly but this is an other issue and doesn't matter (for now).

Thank you very much for your work and fast support!

**Comment by cmeeren** [comment]
v1.3.1 is in the pipeline now and will be published shortly.

Thank _you_ for a short and concise problem description and solution suggestion. That made it a lot easier to fix this!
