### ISSUE TITLE
Consider generating "full" records for Script-based results

### ISSUE THREAD

**Issue by isaacabraham** [cmeeren/Facil#17]
Facil currently generates anonymous records for the results from scripts. Consider changing these to "full" records, or at the least aliasing the anonymous record and making the alias public so that it can be utilised elsewhere e.g. in mapping code.

**Comment by cmeeren** [comment]
Facil supports the same result types for scripts as for records:

Here's the reference section for scripts:

https://github.com/cmeeren/Facil/blob/bf8a2597d428e43b313f6337f339b9d89f726320/facil_reference.yaml#L166-L171

Here's the result section for procedures:

https://github.com/cmeeren/Facil/blob/bf8a2597d428e43b313f6337f339b9d89f726320/facil_reference.yaml#L81-L94

**Comment by isaacabraham** [comment]
Perfect, apologies for not noticing this.
