### ISSUE TITLE
Should second "update" in docs be "merge"?

### ISSUE THREAD

**Issue by isaacabraham** [cmeeren/Facil#19]
See

https://github.com/cmeeren/Facil/blob/94c4ee7c2942b5dba2f4f7d34a964b3e6e1ad90d/facil_reference.yaml#L315

**Comment by costa100** [comment]
I just tried `- type: merge`  and it worked. So, yes, it should be `merge` instead of `update`.

**Comment by cmeeren** [comment]
Good catch! Fixed in 6649a239b2f3fbc7ae49885a94acd43c61745a12.
