### ISSUE TITLE
suggestion re: regular expressions  case sensitivity

### ISSUE THREAD

**Issue by costa100** [cmeeren/Facil#22]
Hi,
One suggestion, in the yaml you might want to add a comment that the regular expressions used to match sql object names are case sensitive. It kind of took me by surprise, given that the database itself uses case insensitive comparisons, which is the out-of-the-box default for sql server.

You can include the following blurb: The regular expressions used to match sql object names are case sensitive. The regular expression can be prefixed with `(?i)` to make it case insensitive. Ex: `(?i)(dbo\.SomeTableName1|dbo\.SomeTableName2)` .
Thanks

**Comment by cmeeren** [comment]
Thanks, I'll add something like that to the readme and reference YAML.
