### ISSUE TITLE
Allow the customization of the F# records/field names

### ISSUE THREAD

**Issue by costa100** [cmeeren/Facil#26]
Hello,

Sometimes, we have to deal with existing databases that have been developed by other people/projects. In general, more likely there is inconsistency between naming conventions. Some people use pascal case, other use a c style naming conventions (first_name, last_name). It would be nice if Facil offers the option of specifying a naming conversion scheme when generating the F# records. It would be best if the naming convention can be specified, per connection, per sets of objects selected through the include/exclude options down to the column.

Possible options: AsIs, PascalCase, CStyle, CamelCase ( not sure about this one).
Example: 
Database: first_name
AsIs: first_name
PascalCase: FirstName
CStyle: first_name
CamelCase: firstName

I am not sure if we need to go as far as specifying Plural or Singular.

In addition to this, it might be nice to offer the option of overriding the name of a record regardless of the conversion scheme.

What do you think?

**Comment by cmeeren** [comment]
Thank you for the feature request. I consider it in-scope for Facil. However, for the reasons below, I'm going to give this a pass, at least for the foreseeable future:

* It would require quite a bit of work to implement, as it touches on all parts of the generated code - table DTOs, parameters, output columns, etc.
* This would non-trivially increase the complexity and therefore maintenance burden of Facil.
* I have limited capacity for OSS maintenance.
* Facil only provides the data access layer and stops at the DTO level, letting you map to your domain objects however you want. I don't think naming conventions in DTO objects, scripts, etc. is as important as in "normal" code. Generally, I find it better if the type/field names match the table/column names in the DB, just as I find it better that types serialized to JSON are serialized exactly as is, with fields named e.g. `camelCase` if that's what you want in the output.

Closing this for now. Feel free to continue the discussion if you strongly disagree.
