### ISSUE TITLE
Question (not an issue) re: SqlDataReader - getting fields values by field ordinal number vs by field name

### ISSUE THREAD

**Issue by costa100** [cmeeren/Facil#30]
Hi,

I am just curios, in the generated code, why do you get the field values by ordinal number instead of using the field names? I assume that it's faster, but how much faster? Did you run any tests?

```
let mutable ``ordinal_ID`` = 0

let initOrdinals (reader: SqlDataReader) =
        ``ordinal_ID`` <- reader.GetOrdinal "ID"

let getItem (reader: SqlDataReader) =
  let ``ID`` = reader.GetInt32 ``ordinal_ID``
```

Thanks

**Comment by cmeeren** [comment]
I haven't benchmarked, but I did research this when making the decision. I don't remember now what sources I used or how much faster it allegedly was, but as you guess, it is faster. More so the more rows you read. It is an optimization I do not intend to remove, unless someone can present benchmarks for a wide range of configurations/situations that show that it provides no benefits or actually has a meaningful negative impact.

**Comment by costa100** [comment]
> It is an optimization I do not intend to remove

For sure. It's all good - you want to squeeze as much speed as you can. I asked because in the code that I usually write manually, I get  field values by name. On the other hand the number of records that I got was not that high.

Thank you

**Comment by cmeeren** [comment]
> I asked because in the code that I usually write manually, I get field values by name.

Same here, but since Facil auto-generates code, I saw little reason not to make this optimization.
