### ISSUE TITLE
Runtime exception running console app with Facil 2.2.0

### ISSUE THREAD

**Issue by costa100** [cmeeren/Facil#33]
Hi,

I upgraded to Facil 2.2.0 - thank you for making all the changes.
However, now, when I run my console app I get this exception:

```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Facil.Runtime.CSharp, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Facil.Runtime.CSharp, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null'
```

The version that is in the bin folder is 2.1.2. Any idea on how to fix this? Or is it something that you have to fix?

Thank you

**Comment by costa100** [comment]
I think there is something wrong with Rider.net . I compiled the solution in VS 2022 and it works properly.

**Comment by costa100** [comment]
Sorry for the false alarm. After I built the solution in VS 2022, I restarted Rider.Net (it's version 2021.3.2) and it seems it's got its brains back. It was really weird. 🤷‍♂️

**Comment by cmeeren** [comment]
Yeah, stuff like that happens sometimes even with VS. Probably a cache issue. Whenever stuff like that happens, just delete all obj and bin folders. If that doesn't solve it, repeat and also delete the `.vs` folder. If that still doesn't solve it, repeat and delete your NuGet cache `the .nuget` folder in your home folder).
