### ISSUE TITLE
Ignore unsupported columns

### ISSUE THREAD

**Issue by davidtme** [cmeeren/Facil#4]
While trying to run against a project I get the following error:

```
Facil : error : System.Exception: Error getting table DTOs
 ---> System.Exception: Unknown SQL system type ID: 240
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1433.Invoke(String message) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1433
   at Facil.Db.typeInfo@496-18.Invoke(Unit unitVar0) in C:\Dev\Facil\src\Facil.Generator\Db.fs:line 496
   at Facil.Db.getTableDtos(FSharpMap`2 sysTypeIdLookup, SqlConnection conn) in C:\Dev\Facil\src\Facil.Generator\Db.fs:line 490
   --- End of inner exception stack trace ---
   at Facil.Db.getTableDtos(FSharpMap`2 sysTypeIdLookup, SqlConnection conn) in C:\Dev\Facil\src\Facil.Generator\Db.fs:line 527
   at Facil.Db.getEverything(RuleSet cfg, String fullYamlPath, FSharpList`1 scriptsWithoutParamsOrResultSetsOrTempTables, SqlConnection conn) in C:\Dev\Facil\src\Facil.Generator\Db.fs:line 694
   at Facil.Program.regenerate@82.Invoke(Unit unitVar0) in C:\Dev\Facil\src\Facil.Generator\Program.fs:line 90
   at Facil.Program.main(String[] argv) in C:\Dev\Facil\src\Facil.Generator\Program.fs:line 125
```

I have a feeling it's the sql spatial type, this project uses the geography::Point type.

**Comment by cmeeren** [comment]
Thanks. I have not implemented anything relating to spatial types. I don't even know how they work; never used them and never researched them. Does it map cleanly to any .NET type? E.g. like here:

https://github.com/cmeeren/Facil/blob/ad8a8abcc5645803c1d8a5c93270345b4056b2bf/src/Facil.Generator/Domain.fs#L52-L65

If not, do you know how it can be supported?

**Comment by davidtme** [comment]
To be honest I'd be happy if they didn't get implement and the columns just got skipped (maybe with warning but not really bothered).  None of our scripts use them it's just the table dtos picking them up.  We don't uses them within dotnet because they are a pain.

**Comment by cmeeren** [comment]
I see. I think I'll ignore unsupported output columns with a warning, and add the capability to configure ignored columns in order to silence the warning.

**Comment by cmeeren** [comment]
I have now added the ability to configure skipped columns in scripts, procedures, and table DTOs. Check out the nupkg available [here](https://ci.appveyor.com/project/cmeeren/facil/builds/37019734/artifacts) (or a more recent build). Let me know if it works and if I should release it (as well as the temp table feature).

Usage:

https://github.com/cmeeren/Facil/blob/3fd3ec028626ae685718d7d164df33c6f2a4bb06/facil_reference.yaml#L253-L261

**Comment by davidtme** [comment]
@cmeeren Thanks for the quick turn around. I'm back at work tomorrow and I'll give it another go.

**Comment by cmeeren** [comment]
I'll publish this and the temp table stuff Monday morning (UTC) because I need to migrate some production systems to Facil then. Just mentioning it in case you have any last-minute feedback.

**Comment by cmeeren** [comment]
Published in 0.1.3.

**Comment by davidtme** [comment]
@cmeeren I couldn't get this to run.  I've looked at the new code and I think it's this line

https://github.com/cmeeren/Facil/blob/7a8453c7586e8bf0688755c146e79bcbb444e99f/src/Facil.Generator/Db.fs#L587#

I switched it to ```

      let shouldSkipCol =
        RuleSet.getEffectiveTableDtoRuleFor schemaName tableName cfg
        |> fun r -> r.Columns
        |> Map.tryFind colName // Change here
        |> Option.bind (fun c -> c.Skip)
        |> Option.defaultValue false

```

and the generator worked

**Comment by cmeeren** [comment]
Thanks, I'll add a test and publish a new version.
