### ISSUE TITLE
Upgrade to Microsoft.Extensions.Configuration 6.0.1 breaks environment variable reading

### ISSUE THREAD

**Issue by mauriciomagni** [cmeeren/Facil#41]
Hello @cmeeren 

As it happened sometime ago, Microsoft has broken (or at least changed) the reading of environment variables with version 6.0.1 of:
open Microsoft.Extensions.Configuration
open Microsoft.Extensions.Configuration.EnvironmentVariables

Do you mind keeping these references to 6.0.0 until it is fixed?

Kind regards,
Mauricio

**Comment by cmeeren** [comment]
Ah, seems it won't be fixed until 7.x. I'll revert.

**Comment by cmeeren** [comment]
Publishing fix in v2.5.7.

**Comment by mauriciomagni** [comment]
thanks!

**Comment by cmeeren** [comment]
For what it's worth, I have also added a comment that should hopefully prevent me doing this again:

https://github.com/cmeeren/Facil/blob/fe8253635fbb8393bf0b78d7642bd0af4da87cab/src/Facil.Generator/Facil.Generator.fsproj#L36-L37
