### ISSUE TITLE
Support for F#9 Non-nullable ref types

### ISSUE THREAD

**Issue by isaacabraham** [cmeeren/Facil#64]
This can be achieved (I believe) by using `Unchecked.defaultOf<_>` in place of the `null` values that are supplied for e.g. some ctors. Or probably there's another way of doing this.

**Comment by cmeeren** [comment]
Seems like an innocuous enough change. I haven't gotten to F# 9 yet in my work. Will probably be another week at least before I can have a look at it.

**Comment by isaacabraham** [comment]
I'm just testing that out manually - seems like it doesn't work. But an even easier change for you would be to simply add

```fsharp
#nowarn FS3261
```

Probably alongside the existing `nowarn` that's already there.

**Comment by isaacabraham** [comment]
Thank you, great suggestion!

**Comment by cmeeren** [comment]
Fixed in a024b676d286156eae9f4c21989eb174ae78eb78 by disabling FS3261. That struck me as the best solution. Anything more means I would have to require FSharp.Core >= 9.0.100. Release 2.14.0 is in the pipeline.
